// File generated by quicktype with modifications
/* eslint-disable no-unused-vars */
export default interface Crashdump {
  code: { [key: string]: string };
  error: Error;
  extensions: { [key: string]: string };
  format_version: number;
  general: General;
  jit_mode?: number;
  lastError: LastError;
  parameters: string[];
  phpinfo: string;
  plugin: string;
  plugin_involvement: PluginInvolvement;
  plugins: { [key: string]: Plugin };
  'pocketmine.yml'?: string;
  'server.properties'?: string;
  time: number;
  trace: string[];
  uptime: number;
}
interface Error {
  file: string;
  line: number;
  message: string;
  type: string;
}
interface General {
  base_version: string;
  build: number;
  composer_libraries: { [key: string]: string };
  git: string;
  is_dev: boolean;
  name: string;
  os: string;
  php: string;
  php_os: string;
  protocol: number;
  uname: string;
  zend: string;
}
interface LastError {
  file: string;
  fullFile: string;
  line: number;
  message: string;
  trace: string[];
  type: string;
}
enum PluginInvolvement {
  Direct = 'direct',
  Indirect = 'indirect',
  None = 'none',
}
interface Plugin {
  api: string[];
  authors: string[];
  depends?: string[];
  enabled: boolean;
  load: Load;
  main?: string;
  name: string;
  softDepends?: string[];
  version: string;
  website?: string;
}
enum Load {
  Postworld = 'POSTWORLD',
  Startup = 'STARTUP',
}
